// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Status string `json:"status"`
	User   *User  `json:"user"`
}

type Mutation struct {
}

type NewArticle struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
