// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID    string `json:"id"`
	Text  string `json:"text"`
	Draft bool   `json:"draft"`
	User  *User  `json:"user"`
}

type Mutation struct {
}

type NewArticle struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
