// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Status  string `json:"status"`
	User    *User  `json:"user"`
}

type Mutation struct {
}

type NewArticle struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Status  string `json:"status"`
	UserID  string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
